### ISSUE TITLE
D starter workflow based on setup-dlang

### ISSUE THREAD

**Issue by andre2007** [mihails-strasuns/setup-dlang#1]
Ideally the [D starter workflow](https://github.com/actions/starter-workflows/pull/74) should be based on your work.

I am not sure wheter this implies that your repository is moved to the organisation https://github.com/actions.

@mihails-strasuns @ErnyTech Any chance to make this happen?

**Comment by mihails-strasuns** [comment]
Yeah, looks reasonable. Will need a minor enhancement for this action to specify a default compiler and os value but otherwise should "just work".

**Comment by mihails-strasuns** [comment]
With https://github.com/mihails-strasuns/setup-dlang/releases/tag/v0.2.0 it is now possible to use the pipeline definition from https://github.com/mihails-strasuns/setup-dlang/issues/1#issuecomment-530977884 - it supports `dmd-latest` as a version and uses it by default.

Is there anything else I can do for this issue?

**Comment by ErnyTech** [comment]
Really good, now you can use it for starter workflow

**Comment by andre2007** [comment]
@ErnyTech the runtime is also 4 times faster than the container approach.

**Comment by mihails-strasuns** [comment]
I am closing this for now. Please open more specific issues if there is anything you'd like me to do for this purpose.
