### ISSUE TITLE
Create/use a dummy Github account for API interaction

### ISSUE THREAD

**Issue by mihails-strasuns** [mihails-strasuns/setup-dlang#14]
Tracked down current sporadic failures of `ldc-master` job to this:

```
{"message":"API rate limit exceeded for 199.7.166.17. (But here's the good news: Authenticated requests get a higher rate limit. Check out the documentation for more details.)","documentation_url":"https://developer.github.com/v3/#rate-limiting"}
```

A simple solution would be to create a dummy account with no access to anything and embed an access token for it into setup-dlang code. At least I can't think of any security implications for that.

Any other ideas are welcome.

**Comment by WebFreak001** [comment]
having a token variable which you can optionally assign your github secret to, which defaults to some application value, should work well.

Assignable so it can be made more reliable if wanted
