### ISSUE TITLE
Export LD_LIBRARY_PATH or similiar, so projects doing a shared link against libphobos work

### ISSUE THREAD

**Issue by Cogitri** [mihails-strasuns/setup-dlang#18]
Hello,

first of, thanks for this action :)

[My project](https://github.com/Cogitri/corecollector) builds fine thanks to it now, but the tests are failing because the test exe can't find libphobos (I link everything shared). See https://github.com/Cogitri/corecollector/commit/f7a459971bc8c2019c2933227b8c4e0d84f314dd/checks?check_suite_id=374129330 for the log. I suppose on UNIXy OS setting `LD_LIBRARY_PATH` appropriately would fix this, not quite sure how one can do it on Windows.

**Comment by mihails-strasuns** [comment]
Quick searching shows that on Windows regular `PATH` may be used for this purpose too.

Mandatory warning - the resulting binary will still be rather unusable outside of the action context (i.e. can't just artifact it for distribution). But I presume you need it for testing only.

**Comment by Cogitri** [comment]
Yup, thanks for the warning but it's only meant for running my tests :)

**Comment by mihails-strasuns** [comment]
Curious, it looks like there are no dlls in Windows archives for neither dmd nor ldc. I'll ignore it for now until someone more knowledgeable explains what to do.

**Comment by Cogitri** [comment]
Hm, dunno about that but then I don't use Windows

**Comment by mihails-strasuns** [comment]
@Cogitri can you please confirm that https://github.com/mihails-strasuns/setup-dlang/pull/21 works for you? (by using `mihails-strasuns/setup-dlang@ld_path`)

**Comment by mihails-strasuns** [comment]
https://github.com/mihails-strasuns/setup-dlang/releases/tag/v0.5.0
