### ISSUE TITLE
Help wanted: build fails in Windows

### ISSUE THREAD

**Issue by neilsf** [mihails-strasuns/setup-dlang#22]
Hi

I'm really sorry for spamming your issue board but I don't really know where to start debugging my issue and I thought maybe you can give some hint.

I'm using your action to build my D language project: https://github.com/neilsf/XC-BASIC and it works perfectly for ubuntu-latest and macOS-latest. However, it fails for Windows with this message:

     core.exception.OutOfMemoryError@src\core\exception.d(647): Memory allocation failed

Which is weird because it never happened in my local instance. I have tried to add the `--build-mode=singleFile` option to DUB as well as passing the `-lowmem` and `-m64` flags to DMD as these are the only options I know that should reduce RAM usage. No luck.

Can you suggest anything else I could try? Do you think it's an issue in GitHub Actions?

Thanks and keep up the great work.

**Comment by WebFreak001** [comment]
try starting dub with `-v` to see command invocations

**Comment by mihails-strasuns** [comment]
Per https://help.github.com/en/actions/reference/virtual-environments-for-github-hosted-runners runners only have 7GB RAM which is likely less than on your dev machine - and the D compiler can be very memory hungry.

You can try using `dub build --build-mode=singleFile` to try a slower build model where each file is compiled separately.

**Comment by neilsf** [comment]
@mihails-strasuns thanks. I can build my project in a Win10 VM with as low as 2GBs of RAM...it takes some time to compile but it works :-) What I haven't tried though is LDC or maybe an earlier version of DMD. I think I'll play around with them.

@WebFreak001 thanks. I added the `-v` flag but I can't see anything noticeable in the output. This is were it fails:

     Compiling source\app.d...
     C:\hostedtoolcache\windows\dc\dmd-2.090.1\x64\dmd2\windows\bin\dmd.exe -Jlib/ -lowmem -m64 -m64 -debug -g -w -version=Have_xcbasic64 -version=Have_dini -version=Have_pegged -Isource -IC:\Users\runneradmin\AppData\Local\dub\packages\dini-1.0.1\dini\src -IC:\Users\runneradmin\AppData\Local\dub\packages\pegged-0.4.4\pegged source\app.d -c -of.dub\build\application-debug-windows-x86_64-dmd_2090-717E0D57ED327B4D4AC153B45F20273F\app_b58c3661.obj -vcolumns 

`-debug` and `-g` are not really necessary but my intuition suggests that they don't increase RAM usage significantly, do they?

Thank you guys, I'll keep on trying. I'll update you if I find a solution.

**Comment by WebFreak001** [comment]
tip for pegged:

move your grammar (package language.grammar for you) into a separate subpackage and have a function to return the parse tree.

It only compiles the grammar once then until you next change it, reduces the memory usage and reduces the compilation time significantly.

**Comment by neilsf** [comment]
Hey @WebFreak001 that worked!!!! Many thanks! It radically reduced compile time on my local instance as well.
