### ISSUE TITLE
No need for a GITHUB_TOKEN to query LDC latest

### ISSUE THREAD

**Issue by wilzbach** [mihails-strasuns/setup-dlang#26]
I was curious about the need for a GITHUB_TOKEN. With a glance from my phone I think that you aren't aware that we have solved the same problem (of getting the version of LDC latest) for the install script:

https://github.com/dlang/installer/blob/master/script/install.sh#L560

CC @Geod24

**Comment by mihails-strasuns** [comment]
@wilzbach hi, thanks - currently github API is used to figure out the latest nightly build (from https://github.com/ldc-developers/ldc/releases/tag/CI), not the latest regular build. For regular ones I am indeed using the same approach you have linked.

Note though that after the patch from @Geod24 merged yesterday it is not needed to supply GITHUB_TOKEN explicitly anymore - it will be provided but github itself. This is why it is also removed from the README now.

**Comment by mihails-strasuns** [comment]
To elaborate more, I have initially used https://github.com/dlang/installer/blob/f0020fba1752e9d1ef81f2aa4bec7bfedb8dd4d8/script/install.sh#L571 for LDC CI builds but it has proven unreliable for CI purpose because it depends on the availability of additional 3d-party url.

**Comment by mihails-strasuns** [comment]
@wilzbach ok to close or you see an area for improvement here?

**Comment by wilzbach** [comment]
So a user doesn't even have to set the GITHUB_TOKEN?
Well, I wasn't aware of that. I just saw @Geod24 PRs at the dlang repositories and your source code and figured you might not be aware of our mirror. Thanks for your quick reply!

**Comment by Geod24** [comment]
> So a user doesn't even have to set the GITHUB_TOKEN?

Not with the latest version, it is provided automatically (Github supports default parameters, which is nice).
