### ISSUE TITLE
ldc-latest-ci is broken

### ISSUE THREAD

**Issue by Geod24** [mihails-strasuns/setup-dlang#6]
Since yesterday, using ldc-latest-ci is broken.
This is probably due to a change upstream. The error being triggered is [here](https://github.com/mihails-strasuns/setup-dlang/blob/785b25c9c8ab3684326846d3e7d187a35b1a4a20/src/compiler.ts#L130).

Going to http://thecybershadow.net/d/github-ldc/ the answer I currently get is:
```
https://github.com/ldc-developers/ldc/releases/download/CI/ldc2-cac80e12-linux-aarch64.tar.xz
https://github.com/ldc-developers/ldc/releases/download/CI/ldc-4a68a005-src.zip
https://github.com/ldc-developers/ldc/releases/download/CI/ldc2-4a68a005-android-armv7a.tar.xz
https://github.com/ldc-developers/ldc/releases/download/CI/ldc2-4a68a005-linux-x86_64.tar.xz
https://github.com/ldc-developers/ldc/releases/download/CI/ldc2-4a68a005-osx-x86_64.tar.xz
https://github.com/ldc-developers/ldc/releases/download/CI/ldc2-4a68a005-windows-multilib.7z
https://github.com/ldc-developers/ldc/releases/download/CI/ldc2-4a68a005-windows-x64.7z
https://github.com/ldc-developers/ldc/releases/download/CI/ldc2-4a68a005-windows-x86.7z
```

So, the code is making a wrong assumption, expecting the `src` release to be first.

**Comment by mihails-strasuns** [comment]
@WebFreak001 how about using https://developer.github.com/v3/repos/releases/#list-assets-for-a-release instead and simply fetching latest uploaded asset from the CI release?

**Comment by WebFreak001** [comment]
I think we would also need to fetch a list of commits and search for every commit in the release list because there are no dates in the file names, but then we could use the list assets endpoint.

**Comment by mihails-strasuns** [comment]
Yes, I was referring specifically to list asset API, as it provides a date:

```
    "created_at": "2013-02-27T19:35:32Z",
    "updated_at": "2013-02-27T19:35:32Z",
```

So just getting list of all assets for CI and sorting by "updated_at" should give us the latest uploaded master.

**Comment by Geod24** [comment]
Unfortunately v0.3.1 didn't fix it:

<img width="530" alt="Screen Shot 2019-11-03 at 19 37 33" src="https://user-images.githubusercontent.com/2180215/68083878-94a34b80-fe71-11e9-8088-6cd55a9616dd.png">

https://github.com/bpfkorea/agora/pull/411

**Comment by WebFreak001** [comment]
try restarting the build, it seemed to randomly happen in the PR too

**Comment by Geod24** [comment]
It worked out. So does it mean we're missing a retry mechanism ?

**Comment by mihails-strasuns** [comment]
Would be nice to also understand what exactly the failure is there - I tried running `curl https://api.github.com/repos/LDC-Developers/LDC/releases/tags/CI | jq ".assets[0].name"` in a loop and it has never failed in 100 runs :/

**Comment by WebFreak001** [comment]
you can log error.toString() instead of error.message in the try/catch failure in main which will give you a stacktrace. I did that on `WebFreak001/setup-dlang@fix-ldc` but it didn't crash yet (had about 30 runs so far)

**Comment by mihails-strasuns** [comment]
I've added some more logging and enabled nightly CI re-runs on master so this should come up eventually.

**Comment by mihails-strasuns** [comment]
See https://github.com/mihails-strasuns/setup-dlang/issues/14
